//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSAuthentication.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TesisKiralama
    {
        public int Id { get; set; }
        public Nullable<int> tesisId { get; set; }
        public string kullaniciId { get; set; }
        public string tarih { get; set; }
        public string baslangicSaati { get; set; }
        public string bitisSaati { get; set; }
    }
}
